In [2]:
#예제 1번
symbols = "$*&!@"
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
print(codes)

#예제 2번
symbols = "$*&!@"
codes = [ord(symbol) for symbol in symbols]
print(codes)

[36, 42, 38, 33, 64]
[36, 42, 38, 33, 64]


In [3]:
#예제 3번
x = '"!~$$*&!@'
dummy = [ord(x) for x in x]

print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [4]:
#예제 4번
symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]
print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [5]:
#예제 5번
symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c > 64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function:\n>>> {map(ord, symbols)}")
print(f"List after map:\n>>> {list(map(ord, symbols))}")

[126] 

Map function:
>>> <map object at 0x7fc952a1a4d0>
List after map:
>>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


In [6]:
#예제 6번
colors = ['black', 'white']
sizes = ['S', 'M' ,'L']
tshirts = [(color, size)for color in colors for size in sizes]

print(tshirts)

for color in colors:
  for size in sizes:
    print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [7]:
#예제 7번
symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 38, 35)


In [9]:
#예제 8번
colors = ['black', 'white']
sizes = ['S' , 'M', 'L']

for tshirt in ('{} {}'.format(c, s) for s in sizes for c in colors):
  print(tshirt)

black S
white S
black M
white M
black L
white L


In [12]:
#예제 9번
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
  print('%s/%s' % passport)
  print('{}/{}'.format(passport[0], passport[1]))
  print(f'{passport[0]}/{passport[1]}')

#예제 10번
for country, _ in traveler_ids:
  print(country)


BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855
USA
BRA
ESP


In [19]:
#예제 11번
lax_coordinates = (33.9425, -118.408056)
atitude, longtitude = lax_coordinates
print(atitude)
print(longtitude)

#예제 12번
a= 10; b=20
b, a = a, b
print(a, b)


33.9425
-118.408056
20 10


In [22]:
#예제 13번
divmod(20, 8)

t= (20, 8)
divmod(*t)

quotient, remainder = divmod(*t)
quotient, remainder


(2, 4)

In [23]:
#예제 14번
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [28]:
#예제 15번
a, b, *rest= range(5)
a, b, rest



(0, 1, [2, 3, 4])

In [30]:
#예제 15-1
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [31]:
#예제 15-2
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [32]:
#예제 16번
a, *body, c, d= range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [33]:
#예제 16번-1
*head, b, c, d= range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [34]:
#예제 17번
metro_areas = [
    ("Tokyo", "JP", 36.933, (35, 139)),
    ("Delhi NCR", "IN", 21, (28, 77)),
    ("Mexico City", "MX", 20, (19, -99)),
    ("New York-Newark", "US", 20, (40, -74)),
    ("Sao Paulo", "BR", 19, (-23, -46))
]

print(("{:15} | {:^9} | {:^9}".format("", "lat.", "long.")))
fmt = "{:15} | {:9.4f} | {:9.4f}"

for name, cc, pop, (lat, longi) in metro_areas:
  if longi <= 0:
    print(fmt.format(name, lat, longi))

                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York-Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


In [43]:
#예제 18번
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139.691))
tokyo

tokyo.population
tokyo.coordinates
tokyo[1]

#예제 19번
City._fields

LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208))

delhi = City._make(delhi_data)
delhi._asdict()

for key, value in delhi._asdict().items():
  print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [44]:
#예제 20번
l = [10, 20, 30, 40, 50, 60]
l[:2]
l[2:]
l[:3]
l[3:]


[40, 50, 60]

In [52]:
#예제 21번
invoice = """
0.....6..................25........33......40.......
1909  Pimoroni              $17.50      3     $52.50
1489  6mm Tactile           $4.95       2     $9.90
"""

SKU = slice(0,6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
  print(item[UNIT_PRICE], item[DESCRIPTION])

   $17.5 Pimoroni           
   $4.95 6mm Tactile        
 


In [56]:
#예제 22번
l = list(range(10))
l

l[2:5] = [20,30]
l

del l[5:7]
l

l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [58]:
#예제 23번

l[2:5] = 100

TypeError: must assign iterable to extended slice

In [59]:
#예제 24번
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [61]:
#예제 25번
l = [1,2,3]
l*5

5*'abcd'

'abcdabcdabcdabcdabcd'

In [62]:
#예제 26번
board = [['_'] * 3 for i in range(3)]
board

board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [64]:
#예제 27번
weird_board = [['_'] * 3] * 3
weird_board

weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [65]:
#예제 28번
row = ['_'] *3
board = []
for i in range(3):
  board.append(row)
board[1][2] = 'X'
board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [66]:
#예제 29번
board = []
for i in range(3):
  row = ['_'] * 3
  board.append(row)
print(board)

board[2][0] = 'X'

board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [69]:
#예제 30번
l = [1,2,3]
id(l)

l*=2
l

id(l)

140502637814976

In [70]:
#예제 31번
t = (1, 2, 3)
id(t)

t *= 2
id(t)

140502640728800

In [79]:
#예제 32번
t = (1, 2, [30, 40])

t[2].extend([50, 60])

#예제 33번
print(t)

(1, 2, [30, 40, 50, 60])


In [80]:
#예제 34번
fruits = ['grape' , 'raspberry', 'apple', 'banana']
sorted(fruits)

fruits

sorted(fruits, reverse=True)

sorted(fruits, key=len)

#예제 35번
sorted(fruits, key=len, reverse=True)

fruits

fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [82]:
#예제 36번
from array import array
from random import random

floats = array('d', (random() for _ in range(10**7)))
floats[-1]

0.09710751150655728

In [84]:
#예제 37번
with open('floats.bin' , 'wb') as f:
  floats.tofile(f)

floats2 = array('d')

with open('floats.bin', 'rb') as f:
  floats2.fromfile(f, 10**7)

floats2[-1]

floats == floats2


True

In [87]:
#예제 38번
import array
numbers = array.array('h', [-2,-1,0,1,2])
memv = memoryview(numbers)
len(memv)

memv[0]

memv_oct = memv.cast('B')
memv_oct.tolist()

memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [88]:
#예제 38-1번
data = bytearray(b'hello world')
mv = memoryview(data)

print(mv[0])
mv[0] = 72
print(data)

104
bytearray(b'Hello world')


In [91]:
#예제 39번
import numpy
a = numpy.arange(12)
a

type(a)

numpy.ndarray

In [93]:
#예제 40번
a.shape

a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
#예제 41번
a[2]

a[2, 1]

a[:,1]

array([1, 5, 9])

In [95]:
#예제 42번
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])